In [2]:
from omegaconf import OmegaConf as om
from omegaconf import DictConfig
from typing import cast
import sys 
import os
sys.path.append(os.path.abspath(".."))

from main import build_model



yaml_path = "../yamls/pretrain/micro_dna_monarch-mixer-pretrain-786dim-80m-parameters.yaml"

with open(yaml_path) as f:
    cfg = om.load(f)
cfg = cast(DictConfig, cfg)
print(cfg.max_duration)
model = build_model(cfg.model)

200000ba
Using Monarch Mixer for Sequence Mixing: True
-- Bidirectional: True
-- Using Long Conv Residual: True
-- Hyena w: 10
-- Hyena w mod: 1
-- Hyena filter order: 128
-- Hyena filter dropout: 0.2
-- Hyena filter wd: 0.1
-- Hyena filter emb dim: 5
-- Hyena filter lr: 0.001
-- Hyena filter lr pos emb: 1e-05


In [21]:
from datasets import load_from_disk
from collate import DataCollatorForLanguageModelingSpan
from transformers import AutoTokenizer, Trainer, TrainingArguments

#Load model directly
%env WANDB_PROJECT=singlesamplednam2

tokenizer = AutoTokenizer.from_pretrained("gagneurlab/SpeciesLM", revision="downstream_species_lm")


dataset = load_from_disk("../micro")
dataset = dataset.remove_columns(["species_name", "__index_level_0__"])

data_collator = DataCollatorForLanguageModelingSpan(tokenizer, mlm=True, mlm_probability = 0.02, span_length = 6)

training_args = TrainingArguments(
    output_dir="./results/correct_model_1sample",
    
    max_steps=20000,
    
    seed=17,
    per_device_train_batch_size=1,
    gradient_accumulation_steps=1,
    
    logging_strategy="steps",
    logging_steps=1,
    
    evaluation_strategy="no",
    
    #dataloader_num_workers=4,
    #dataloader_prefetch_factor=2,
    run_name="repo_model_1sample",
    report_to="none" #"wandb"
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=dataset["train"],
    eval_dataset=dataset["test"],
    data_collator=data_collator
)

trainer.train()

env: WANDB_PROJECT=singlesamplednam2


/opt/modules/i12g/anaconda/envs/m2-mixer/lib/python3.9/site-packages/transformers/optimization.py:391: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(


IndexError: Invalid key: 0 is out of bounds for size 0

In [18]:
from torch.utils.data import DataLoader

train_dataloader = DataLoader(dataset["train"], batch_size=1, shuffle=True)
sample = next(iter(train_dataloader))
sample

{'input_ids': [tensor([2]),
  tensor([4203]),
  tensor([1030]),
  tensor([12]),
  tensor([33]),
  tensor([120]),
  tensor([466]),
  tensor([1850]),
  tensor([3292]),
  tensor([865]),
  tensor([3445]),
  tensor([1478]),
  tensor([1804]),
  tensor([3108]),
  tensor([129]),
  tensor([502]),
  tensor([1994]),
  tensor([3868]),
  tensor([3169]),
  tensor([373]),
  tensor([1477]),
  tensor([1797]),
  tensor([3078]),
  tensor([9]),
  tensor([22]),
  tensor([74]),
  tensor([281]),
  tensor([1112]),
  tensor([337]),
  tensor([1334]),
  tensor([1226]),
  tensor([794]),
  tensor([3161]),
  tensor([343]),
  tensor([1357]),
  tensor([1317]),
  tensor([1160]),
  tensor([531]),
  tensor([2112]),
  tensor([242]),
  tensor([953]),
  tensor([3798]),
  tensor([2889]),
  tensor([3349]),
  tensor([1096]),
  tensor([276]),
  tensor([1089]),
  tensor([246]),
  tensor([971]),
  tensor([3870]),
  tensor([3179]),
  tensor([416]),
  tensor([1650]),
  tensor([2492]),
  tensor([1761]),
  tensor([2934]),
  tensor([